classdef Panel < handle
    properties;
        peakPanel;
        valleyPanel;
        slopePanel;
        channelPanel;
        informationPanel;
        callback;
        channel = 1;
        channelNumber = 1;
        
        peakProminence = 1;
        peakDuration = 20;
        valleyProminence = 1;
        valleyDuration = 20;
        slopeHeight = 0.2;
        slopeDuration = 20;
        
        val_peakProminence = 1;
        val_peakDuration = 20;
        val_valleyProminence = 1;
        val_valleyDuration = 20;
        val_slopeHeight = 0.2;
        val_slopeDuration = 20;
        
        amplitude;
        deflection;
        LAT;
        slope;
        duration;
    end
    
    methods
        function self = Panel(w)
            window = w;
            self.peakPanel = uipanel(window, 'Title', 'Peaks',...
                'fontSize', 12, 'Position', [.05, .75, .2, .2]);
            uicontrol(self.peakPanel, 'Style', 'pushbutton',...
                'String', 'Update Info', 'Units', 'normalized',...
                'Position', [.6, .72, .2, .2],...
                'Callback', @self.updateCallback);
            uicontrol(self.peakPanel, 'Style', 'text',...
                'String', 'Prominence:', 'Units', 'normalized',...
                'Position', [.01, .78, .25, .1]);
            uicontrol(self.peakPanel, 'Style', 'text',...
                'String', 'Duration:     ', 'Units', 'normalized',...
                'Position', [.01, .48, .25, .1]);
            
            self.valleyPanel = uipanel(window, 'Title', 'Valleys',...
                'fontSize', 12, 'Position', [.26, .75, .2, .2]);
            uicontrol(self.valleyPanel, 'Style', 'pushbutton',...
                'String', 'Update Info', 'Units', 'normalized',...
                'Position', [.6, .72, .2, .2],...
                'Callback', @self.updateCallback);
            uicontrol(self.valleyPanel, 'Style', 'text',...
                'String', 'Prominence:', 'Units', 'normalized',...
                'Position', [.01, .78, .25, .1]);
            uicontrol(self.valleyPanel, 'Style', 'text',...
                'String', 'Duration:     ', 'Units', 'normalized',...
                'Position', [.01, .48, .25, .1]);
            
            self.slopePanel = uipanel(window, 'Title', 'Slope',...
                'fontSize', 12, 'Position', [.26, .55, .2, .2]);
            uicontrol(self.slopePanel, 'Style', 'pushbutton',...
                'String', 'Update Info', 'Units', 'normalized',...
                'Position', [.6, .72, .2, .2],...
                'Callback', @self.updateCallback);
            uicontrol(self.slopePanel, 'Style', 'text',...
                'String', 'Min Slope:', 'Units', 'normalized',...
                'Position', [.01, .78, .25, .1]);
            uicontrol(self.slopePanel, 'Style', 'text',...
                'String', 'Duration:  ', 'Units', 'normalized',...
                'Position', [.01, .48, .25, .1]);
            
            self.channelPanel = uipanel(window, 'Title', 'Channel',...
                'fontSize', 12, 'Position', [.05, .55, .2, .2]);
            uicontrol(self.channelPanel, 'Style', 'pushbutton',...
                'String', 'Next', 'Units', 'normalized',...
                'Position', [.6, .72, .2, .2],...
                'Callback', @self.nextCallback);
            uicontrol(self.channelPanel, 'Style', 'pushbutton',...
                'String', 'Previous', 'Units', 'normalized',...
                'Position', [.6, .42, .2, .2],...
                'Callback', @self.previousCallback);
            uicontrol(self.channelPanel, 'Style', 'text',...
                'String', 'Channel:     ', 'Units', 'normalized',...
                'Position', [.01, .78, .25, .1]);
            
            self.informationPanel = uipanel(window, 'Title', 'Data Overview',...
                'fontSize', 12, 'Position', [.47, .55, .525, .4]);
            uicontrol(self.informationPanel, 'Style', 'text',...
                'fontSize', 10, 'String', 'Amplitude:',...
                'Units', 'normalized', 'Position', [.05, .8, .1, .1]);
            uicontrol(self.informationPanel, 'Style', 'text',...
                'fontSize', 10, 'String', 'Deflections:',...
                'Units', 'normalized', 'Position', [.40, .8, .1, .1]);
            uicontrol(self.informationPanel, 'Style', 'text',...
                'fontSize', 10, 'String', 'LAT:',...
                'Units', 'normalized', 'Position', [.80, .8, .1, .1]);
            uicontrol(self.informationPanel, 'Style', 'text',...
                'fontSize', 10, 'String', 'Slope:',...
                'Units', 'normalized', 'Position', [.22, .4, .1, .1]);
            uicontrol(self.informationPanel, 'Style', 'text',...
                'fontSize', 10, 'String', 'Duration:',...
                'Units', 'normalized', 'Position', [.62, .4, .1, .1]);
            uicontrol(self.informationPanel, 'Style', 'pushbutton',...
                'String', 'Previous', 'Units', 'normalized',...
                'Position', [.3, .15, .1, .1],...
                'Callback', @self.previousMarkCallback);
            uicontrol(self.informationPanel, 'Style', 'pushbutton',...
                'String', 'Next', 'Units', 'normalized',...
                'Position', [.6, .15, .1, .1],...
                'Callback', @self.nextMarkCallback);
        end
        
        function show(self)
            self.peakProminence = uicontrol(self.peakPanel, 'Style', 'edit',...
                'String', num2str(self.peakProminence), 'Units', 'normalized',...
                'Position', [.3, .72, .2, .2]);
            self.peakDuration = uicontrol(self.peakPanel, 'Style', 'edit',...
                'String', num2str(self.peakDuration), 'Units', 'normalized',...
                'Position', [.3, .42, .2, .2]);
            
            self.valleyProminence = uicontrol(self.valleyPanel, 'Style', 'edit',...
                'String', num2str(self.valleyProminence), 'Units', 'normalized',...
                'Position', [.3, .72, .2, .2]);
            self.valleyDuration = uicontrol(self.valleyPanel, 'Style', 'edit',...
                'String', num2str(self.valleyDuration), 'Units', 'normalized',...
                'Position', [.3, .42, .2, .2]);
            
            self.slopeHeight = uicontrol(self.slopePanel, 'Style', 'edit',...
                'String', num2str(self.slopeHeight), 'Units', 'normalized',...
                'Position', [.3, .72, .2, .2]);
            self.slopeDuration = uicontrol(self.slopePanel, 'Style', 'edit',...
                'String', num2str(self.slopeDuration), 'Units', 'normalized',...
                'Position', [.3, .42, .2, .2]);
            
            self.channelNumber = uicontrol(self.channelPanel, 'Style', 'edit',...
                'String', num2str(self.channel), 'Units', 'normalized',...
                'Position', [.3, .72, .2, .2],...
                'Callback', @self.channelCallback);
            
            self.amplitude = uicontrol(self.informationPanel, 'Style', 'text',...
                'fontSize', 10', 'String', '-', 'Units', 'normalized',...
                'Position', [.15, .8, .1, .1]);
            self.deflection = uicontrol(self.informationPanel, 'Style', 'text',...
                'fontSize', 10', 'String', '-', 'Units', 'normalized',...
                'Position', [.5, .8, .1, .1]);
            self.LAT = uicontrol(self.informationPanel, 'Style', 'text',...
                'fontSize', 10', 'String', '-', 'Units', 'normalized',...
                'Position', [.9, .8, .1, .1]);
            self.slope = uicontrol(self.informationPanel, 'Style', 'text',...
                'fontSize', 10', 'String', '-', 'Units', 'normalized',...
                'Position', [.32, .4, .1, .1]);
            self.duration = uicontrol(self.informationPanel, 'Style', 'text',...
                'fontSize', 10', 'String', '-', 'Units', 'normalized',...
                'Position', [.72, .4, .1, .1]);
        end
        
        function setCallback(self, callback)
            self.callback = callback;
        end
    end
    
    methods (Access = private)
        
        function channelCallback(self, ~, ~, ~)
            self.channel = str2double(self.channelNumber.String);
            self.callback('channel');
        end
        
        function previousCallback(self, ~, ~, ~)
            self.callback('previous');
        end
        
        function previousMarkCallback(self, ~, ~, ~)
            self.callback('previousMark');
        end
        
        function nextCallback(self, ~, ~, ~)
            self.callback('next');
        end
        
        function nextMarkCallback(self, ~, ~, ~)
            self.callback('nextMark');
        end
        
        function updateCallback(self, ~, ~, ~)
            self.val_peakProminence = str2double(self.peakProminence.String);
            self.val_peakDuration = str2double(self.peakDuration.String);
            self.val_valleyProminence = str2double(self.valleyProminence.String);
            self.val_valleyDuration = str2double(self.valleyDuration.String);
            self.val_slopeHeight = str2double(self.slopeHeight.String);
            self.val_slopeDuration = str2double(self.slopeDuration.String);
            
            self.callback('update');
        end
    end
end