classdef Panel < handle
    properties;
        panel;
        callback;
        channel = 1;
        channelNumber = 1;
        
        amp = 1;
        slope = 0.2;
        defl = 0;
        dur = 20;
        
        val_amp = 1;
        val_slope = 0.2;
        val_defl = 0;
        val_dur = 20;
    end
    
    methods
        function self = Panel(w)
            window = w;
            self.panel = uipanel(window, 'Title', 'ECG values',...
                'fontSize', 12, 'Position', [.05 .55 .4 .4]);
            %go button
            uicontrol(self.panel, 'Style', 'pushbutton',...
                'String', 'Update Info', 'Units', 'normalized',...
                'Position', [.5, .22, .1, .1],...
                'Callback', @self.updateCallback);
            uicontrol(self.panel, 'Style', 'pushbutton',...
                'String', 'Next', 'Units', 'normalized',...
                'Position', [.5, .42, .1, .1],...
                'Callback', @self.nextCallback);
            uicontrol(self.panel, 'Style', 'pushbutton',...
                'String', 'Previous', 'Units', 'normalized',...
                'Position', [.5, .62, .1, .1],...
                'Callback', @self.previousCallback);
            %input info
            uicontrol(self.panel, 'Style', 'text',...
                'String', 'Prominence: ', 'Units', 'normalized',...
                'Position', [.01, .8, .11, .1]);
            uicontrol(self.panel, 'Style', 'text',...
                'String', 'Slope:        ', 'Units', 'normalized',...
                'Position', [.01, .6, .1, .1]);
            uicontrol(self.panel, 'Style', 'text',...
                'String', 'Deflection:', 'Units', 'normalized',...
                'Position', [.01, .4, .1, .1]);
            uicontrol(self.panel, 'Style', 'text',...
                'String', 'Duration:   ', 'Units', 'normalized',...
                'Position', [.01, .2, .1, .1]);
            uicontrol(self.panel, 'Style', 'text',...
                'String', 'Channel:', 'Units', 'normalized',...
                'Position', [.35, .8, .1, .1]);
        end
        
        function show(self)
            self.amp = uicontrol(self.panel, 'Style', 'edit',...
                'String', num2str(self.amp), 'Units', 'normalized',...
                'Position', [.2, .82, .1, .1]);
            self.slope = uicontrol(self.panel, 'Style', 'edit',...
                'String', num2str(self.slope), 'Units', 'normalized',...
                'Position', [.2, .62, .1, .1]);
            self.defl = uicontrol(self.panel, 'Style', 'edit',...
                'String', num2str(self.defl), 'Units', 'normalized',...
                'Position', [.2, .42, .1, .1]);
            self.dur = uicontrol(self.panel, 'Style', 'edit',...
                'String', num2str(self.dur), 'Units', 'normalized',...
                'Position', [.2, .22, .1, .1]);
            self.channelNumber = uicontrol(self.panel, 'Style', 'edit',...
                'String', num2str(self.channel), 'Units', 'normalized',...
                'Position', [.5, .82, .1, .1],...
                'Callback', @self.channelCallback);
        end
        
        function setCallback(self, callback)
            self.callback = callback;
        end
    end
    
    methods (Access = private)
        function nextCallback(self, ~, ~, ~)
            self.callback('next');
        end
        
        function channelCallback(self, ~, ~, ~)
            self.channel = str2double(self.channelNumber.String);
            self.callback('channel');
        end
        
        function previousCallback(self, ~, ~, ~)
            self.callback('previous');
        end
        
        function updateCallback(self, ~, ~, ~)
            self.val_amp = str2double(self.amp.String);
            self.val_slope = str2double(self.slope.String);
            self.val_defl = str2double(self.defl.String);
            self.val_dur = str2double(self.dur.String);
            self.callback('update');
        end
    end
end